name: NebulaPredictor
dependencies:
  #- python=3.12.0  # Specify the Python version you want to use
  # List your required packages here
  - numpy=1.21.2
  - pandas=1.3.3
  #- flask
  - scikit-learn==1.2.2
  - flask=2.2.5
  - requests=2.26.0
  - matplotlib=3.4.3
  - seaborn=0.11.2
  - lightgbm=4.1.0
  #- datetime=4.3
  - pip
  - pip:
    - ta
  
